baseurl = "https://xxuejie.github.io/"
title = "Less is more"
author = "Xuejie Xiao"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"
staticDir = ["static"]

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Less is More"
  disableWebFonts = false

[[menu.main]]
    name = "About"
    url  = "/about"
[[menu.main]]
    name = "Twitter"
    url  = "https://twitter.com/xxuejie"
[[menu.main]]
    name = "Github"
    url  = "https://github.com/xxuejie"
[[menu.main]]
    name = "RSS"
    url  = "/index.xml"
